import type { Metadata } from "next";
import { Rubik, Lato } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
})

const lato = Lato({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
